#Importing the Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

# Data collection and pre-processing

In [3]:
df = pd.read_csv('/content/Churn_Modelling.csv')

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.shape

(10000, 14)

In [6]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


Row Number, Customer ID, surname are of no use for us in the model, so we neglect them.

But, there are two categorical features (Geography, gender) which have to be encoded.

In [8]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [11]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [10]:
df.groupby('Exited').mean()

<ipython-input-10-e532f3088289>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Exited').mean()


RowNumber    CustomerId  CreditScore        Age    Tenure  \
Exited                                                                
0       5024.694964  1.569117e+07   651.853196  37.408389  5.033279   
1       4905.917526  1.569005e+07   645.351497  44.837997  4.932744   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
Exited                                                           
0       72745.296779       1.544267   0.707146        0.554565   
1       91108.539337       1.475209   0.699067        0.360825   

        EstimatedSalary  
Exited                   
0          99738.391772  
1         101465.677531

#Feature and target seperation

In [12]:
x = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [13]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [14]:
print(y)

[1 0 1 ... 1 1 0]


#Encoding Categorical Features

For Gender column:

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()

In [17]:
x[:,2] = le.fit_transform(x[:, 2])

In [20]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding of Geography column:

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encode', OneHotEncoder(), [1])], remainder='passthrough')

In [24]:
x = np.array(ct.fit_transform(x))

In [25]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Dummy variables are created and moved to the first.

#Train test split

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [28]:
print(x.shape, x_train.shape, x_test.shape)

(10000, 12) (8000, 12) (2000, 12)


#Feature Scaling

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
scaler = StandardScaler()

In [31]:
x_train = scaler.fit_transform(x_train)

In [32]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


Feature scaling for test data:

In [33]:
x_test = scaler.transform(x_test)

# Building the ANN

Initializing the ANN

In [34]:
ann = tf.keras.models.Sequential()

Adding the input layer and first hidden layer

In [35]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the second hidden layer

In [36]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the output layer

In [37]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

#Training the ANN

compiling the ANN

In [38]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Traing with the x_train,y_train

In [39]:
ann.fit(x_train,y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5670 - accuracy: 0.7519
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4944 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4676 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4460 - accuracy: 0.8012
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4288 - accuracy: 0.8138
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4189 - accuracy: 0.8175
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4103 - accuracy: 0.8225
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4033 - accuracy: 0.8248
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3962 - accuracy: 0.8300
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3890 - accura

# Predicting the result of a single observation

Q)Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?

In [40]:
print(ann.predict(scaler.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 126ms/step
[[False]]


A)Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

#Predicting the test data results

In [41]:
test_pred = ann.predict(x_test)
test_pred = (test_pred>0.5)
result = np.concatenate((test_pred.reshape(len(test_pred),1) , y_test.reshape(len(y_test),1)), 1)

63/63 [==============================] - 0s 2ms/step


In [42]:
print(result)

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [44]:
from sklearn.metrics import accuracy_score , confusion_matrix

In [47]:
accuracy = accuracy_score(y_test,test_pred)

In [50]:
print("Accuracy of the ANN is :",round(accuracy*100 , 2),"%")

Accuracy of the ANN is : 85.95 %


In [51]:
# confusion matrix
cm = confusion_matrix(y_test,test_pred)

In [52]:
print(cm)

[[1521   74]
 [ 207  198]]
