In [34]:
import tensorflow

In [35]:
tensorflow.__version__

'2.13.0'

#Importing the dependencies

In [36]:
from tensorflow.keras.preprocessing.text import one_hot

In [37]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [38]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [39]:
voc_size = 10000

#One Hot Representation

In [40]:
oh_rep = [one_hot(words , voc_size) for words in sent]

In [41]:
print(oh_rep)

[[6088, 8105, 6532, 2486], [6088, 8105, 6532, 9239], [6088, 3661, 6532, 3431], [624, 8874, 3621, 4264, 2303], [624, 8874, 3621, 4264, 4598], [7027, 6088, 2814, 6532, 3494], [6255, 1503, 5691, 4264]]


We can see that the first and second sentences are almost same except milk and juice. So, in one hot representation also we can see that the first three index are same, only change is  with the last word.

#Word Embedding representation


In [42]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [43]:
import numpy as np

**Padding the sentences:**

To make all the sentences in the input of the same size.

In [44]:
sentence_length = 8
padded_sentences = pad_sequences(oh_rep, padding = 'pre', maxlen = sentence_length)


In [45]:
print(padded_sentences)

[[   0    0    0    0 6088 8105 6532 2486]
 [   0    0    0    0 6088 8105 6532 9239]
 [   0    0    0    0 6088 3661 6532 3431]
 [   0    0    0  624 8874 3621 4264 2303]
 [   0    0    0  624 8874 3621 4264 4598]
 [   0    0    0 7027 6088 2814 6532 3494]
 [   0    0    0    0 6255 1503 5691 4264]]


In [46]:
dimenssions = 10

#Creating a neural network

In [47]:
model = Sequential()

In [48]:
model.add(Embedding(voc_size, dimenssions, input_length = sentence_length))

In [49]:
model.compile(optimizer = 'adam', loss = 'MSE')

In [50]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


#Prediction

In [51]:
print(model.predict(padded_sentences))

1/1 [==============================] - 0s 49ms/step
[[[ 0.00939335 -0.01626307 -0.0233663   0.03803957 -0.03033216
   -0.03934549  0.0284108   0.02374229 -0.0086539   0.01229434]
  [ 0.00939335 -0.01626307 -0.0233663   0.03803957 -0.03033216
   -0.03934549  0.0284108   0.02374229 -0.0086539   0.01229434]
  [ 0.00939335 -0.01626307 -0.0233663   0.03803957 -0.03033216
   -0.03934549  0.0284108   0.02374229 -0.0086539   0.01229434]
  [ 0.00939335 -0.01626307 -0.0233663   0.03803957 -0.03033216
   -0.03934549  0.0284108   0.02374229 -0.0086539   0.01229434]
  [ 0.04570354 -0.01864463  0.02739965  0.02994991 -0.00467879
   -0.03293389 -0.00101417  0.04639691 -0.01410612 -0.02978016]
  [-0.00138503  0.01930794  0.00813569  0.03091837 -0.03367124
    0.04162896  0.04068439 -0.04358348 -0.03642073  0.02682083]
  [-0.04069532  0.00155795 -0.04220274  0.04383827  0.04611092
   -0.02791873  0.00682939  0.0276535  -0.0040136  -0.02431626]
  [ 0.03869691 -0.01224489  0.03216405 -0.04431393 -0.04623

In [32]:
print(padded_sentences[0])

[   0    0    0    0 6088 8105 6532 2486]


In [33]:
print(model.predict(padded_sentences[0]))

1/1 [==============================] - 0s 45ms/step
[[-0.02274463  0.01609537 -0.04618256 -0.03537776  0.04711384 -0.01448628
  -0.03467096  0.00581876  0.00612389 -0.01603583]
 [-0.02274463  0.01609537 -0.04618256 -0.03537776  0.04711384 -0.01448628
  -0.03467096  0.00581876  0.00612389 -0.01603583]
 [-0.02274463  0.01609537 -0.04618256 -0.03537776  0.04711384 -0.01448628
  -0.03467096  0.00581876  0.00612389 -0.01603583]
 [-0.02274463  0.01609537 -0.04618256 -0.03537776  0.04711384 -0.01448628
  -0.03467096  0.00581876  0.00612389 -0.01603583]
 [ 0.01456554 -0.00662792  0.02865719 -0.04659512  0.03355599  0.04488892
  -0.01079402  0.03536079  0.04856053 -0.04767594]
 [-0.04008644  0.00337918  0.01949327  0.01456388 -0.02367522 -0.00827055
  -0.04672464  0.00955298 -0.01097982 -0.04517615]
 [ 0.00344933  0.04629738 -0.04197284 -0.00106252 -0.00517175 -0.00040382
  -0.01806376 -0.04377942 -0.00800321 -0.03645028]
 [-0.04647747 -0.04369252 -0.04434879 -0.01711377  0.00178383 -0.00649912