# Matrices and working in python

In [1]:
import numpy as np

1) Creating a matrix in numpy

In [3]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

2) creating a random value matrix

In [4]:
random_mat = np.random.rand(4,6)

In [5]:
print(random_mat)

[[0.36369749 0.49169045 0.28135202 0.40645422 0.8128728  0.77819703]
 [0.76075718 0.29490401 0.00908472 0.27199089 0.54079013 0.4724316 ]
 [0.26502544 0.77911017 0.91713226 0.19123044 0.30700904 0.67813228]
 [0.47353832 0.41213665 0.48160169 0.02623827 0.58121426 0.24104775]]


3) Creating a matrix with random integers:

In [7]:
r = np.random.randint(100, size = (4,5))
print(r)

[[98 45 84 77 56]
 [ 9 23 54 31 94]
 [95 65 43 31 75]
 [44 11 80 70 20]]


4) with all ones and zeros

In [9]:
o = np.ones((3,5),dtype = 'int')
print(o)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
z = np.zeros((4,4), dtype = 'int')
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


5) Identity matrix:

In [11]:
i = np.eye(3,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


6) Transpose of a matrix:

In [12]:
transpose_of_r = np.transpose(r)
print(transpose_of_r)

[[98  9 95 44]
 [45 23 65 11]
 [84 54 43 80]
 [77 31 31 70]
 [56 94 75 20]]
