# Basic Operations on matrices in python

In [1]:
import numpy as np

1) Matrix addition:

In [3]:
a = np.random.randint(100, size = (3,3))
b = np.random.randint(50, size = (3,3))

In [5]:
print(a)
print(b)

[[63 98 62]
 [91 91 23]
 [41  0 31]]
[[21 13  8]
 [13 36 14]
 [26 43 45]]


In [ ]:
# sum = a + b
sum = np.add(a,b)
print(sum)

2) Matrix Subtraction:

In [6]:
a = np.random.randint(100, size = (3,3))
b = np.random.randint(50, size = (3,3))

In [7]:
print(a)
print(b)

[[38 56  9]
 [ 4 76 65]
 [35 47  6]]
[[ 6 49 33]
 [38 15 23]
 [24 47  5]]


In [8]:
# diff = a - b
diff = np.subtract(a,b)
print(diff)

[[ 32   7 -24]
 [-34  61  42]
 [ 11   0   1]]


3) Multiplying by a scalar:

In [10]:
m = np.random.randint(50, size = (3,3))
s = 5
product = np.multiply(m,s)
print(product)

[[ 25 220 225]
 [ 85  20 135]
 [240  40 220]]


4) Multiplying two matrices:

In [11]:
a = np.random.randint(20 , size = (3,4))
b = np.random.randint(10, size = (4,2))
prod = np.dot(a,b)

In [12]:
print(prod)

[[238  82]
 [246  82]
 [322  82]]


In [13]:
prod.shape

(3, 2)