#NUMPY - Numerical Python

Advabtages of Numpy arrays over list and tuple:


1.   Allows several Mathematical operations
2.   Faster operations
**But numpy arrays data should be homogenous unlike lists which can store multiple datatypes**



In [1]:
import numpy as np

**List v/s Numpy ---> time taken**

In [2]:
from time import process_time

1) Time taken by a list

In [8]:
python_list = [i for i in range(10000)] # creating a list with numbers from 0 to 9999 using a for loop
start_time = process_time()
python_list = [i+5 for i in python_list] # adding 5 to every element of the list
end_time = process_time()
print(end_time - start_time)

0.0017233989999994037


2) Time taken for numpy array

In [7]:
np_array = np.array([i for i in range(10000)])
st = process_time()
np_array += 5
et = process_time()
print(et-st)

0.00014954599999938978


#Numpy arrays


In [9]:
list = [1,2,3,4,5]
print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [10]:
# creating a 1-d np array
np_list = np.array([1,2,3,4,5])
print(np_list)
type(np_list) # gives numpy.ndarray => ndarray is n-dimessional array, so numpy arrays are simliar to matrixes

[1 2 3 4 5]


numpy.ndarray

In [11]:
# shape
a = np.array([1,2,3,4])
a.shape # ---> gives the number of rows and columns in the np array

(4,)

In [14]:
# creating a 2-d np array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape # => (2,4) no.of rows = 2, no. of colums = 4

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [15]:
#putting floating point numbers in np array
c = np.array([(1,2,3,4),(5,6,7,8)], dtype = float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#Initial place holders in numpy arrays

The initial values in the np array

In [18]:
# a numpy array of zeros
x = np.zeros((4,6))
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
# a numpy array with all ones
y = np.ones((3,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
# a numpy array with a particular value
f = np.full((3,3),7) # np.full(shape, value)
print(f)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [21]:
# creating an identity matrix
i = np.eye(5) # np.eye(size) => because in identity matrix no. of rows = no. of columns
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
# creating a np array with random values
# !!! Note that all the values will be between 0 and 1 , that are all floating point numbers
r = np.random.random((3,4))
print(r)

[[0.60453108 0.89035936 0.84468086 0.28357207]
 [0.48247608 0.20649494 0.89554261 0.09947944]
 [0.11320667 0.24776067 0.35448917 0.81719722]]


In [23]:
# creating a random integer numpy array within a given range
ri = np.random.randint(1,100,(4,4)) # ==> np.random.randint(start,end,shape)
print(ri)

[[75 28 69 62]
 [12 38  9 12]
 [31 88  3  5]
 [25 38  8 16]]


In [25]:
# creating an array of evenly spaced values
evenlySpaced = np.linspace(10,30,6) # => np.linspace(start,end,no.of values we want in that range)
print(evenlySpaced)

[10. 14. 18. 22. 26. 30.]


In [27]:
 # evenly spaced array with specifying the step
 e = np.arange(10,30,5) # => np.arange(start,end,step size)
 print(e)

[10 15 20 25]


#Converting list to np array

In [28]:
# list to numpy array
ls = [1,2,5,6,7]
np_arr = np.asarray(ls)
print(np_arr)
type(np_arr)

[1 2 5 6 7]


numpy.ndarray

In [29]:
# tuple to numpy array
tup = (1,3,5,7)
npAr = np.asarray(tup)
print(npAr)
type(npAr)

[1 3 5 7]


numpy.ndarray

#Analyzing a numpy array

In [30]:
n = np.random.randint(1,100,(5,5))
print(n)

[[47 72 17 74 61]
 [67 10 95 41  1]
 [72 52 47 52 59]
 [75 94 69 10 10]
 [36 44  2 74 48]]


In [31]:
# shape of the array
n.shape

(5, 5)

In [33]:
# dimessions of the array
print(n.ndim)

2


In [34]:
# no. of elements in the array
print(n.size)

25


In [35]:
# checking data type of the values in the array
print(c.dtype)

float64


**Mathematical operations that can be performed on a np_array:**

In [36]:
l1 = [1,2,3,4]
l2 = [5,6,7]
print(l1+l2) # it concatnates the lists

[1, 2, 3, 4, 5, 6, 7]


In [37]:
p = np.random.randint(0,10,(3,3))
q = np.random.randint(10,20,(3,3))
print(p)
print(q)

[[0 2 6]
 [2 3 6]
 [2 0 7]]
[[14 12 11]
 [16 11 13]
 [16 10 12]]


In [38]:
# operations in numpy arrays , not like lists
print(p+q)
print(p-q)
print(p*q)
print(p/q)

[[14 14 17]
 [18 14 19]
 [18 10 19]]
[[-14 -10  -5]
 [-14  -8  -7]
 [-14 -10  -5]]
[[ 0 24 66]
 [32 33 78]
 [32  0 84]]
[[0.         0.16666667 0.54545455]
 [0.125      0.27272727 0.46153846]
 [0.125      0.         0.58333333]]


In [40]:
# another way of adding, subtracting the arrays
print(np.add(p,q))
print(np.subtract(p,q))
print(np.multiply(p,q))
print(np.divide(p,q))

[[14 14 17]
 [18 14 19]
 [18 10 19]]
[[-14 -10  -5]
 [-14  -8  -7]
 [-14 -10  -5]]
[[ 0 24 66]
 [32 33 78]
 [32  0 84]]
[[0.         0.16666667 0.54545455]
 [0.125      0.27272727 0.46153846]
 [0.125      0.         0.58333333]]


**Array manipulation**

In [41]:
# Transpose of a matrix
arr = np.random.randint(0,15,(2,3))
print(arr)
print(arr.shape)

[[10  1  0]
 [ 8  4  8]]
(2, 3)


In [42]:
trans = np.transpose(arr)
print(trans)
print(trans.shape)

[[10  8]
 [ 1  4]
 [ 0  8]]
(3, 2)


In [43]:
t2 = trans.T
print(t2)
print(t2.shape)

[[10  1  0]
 [ 8  4  8]]
(2, 3)


In [44]:
# Reshaping an array
s = np.random.randint(0,20,(4,3))
print(s)
print(s.shape)

[[17  4 19]
 [16  9  5]
 [18 10 19]
 [14  6  9]]
(4, 3)


In [47]:
re = s.reshape(6,2)
print(re)
print(re.shape)

[[17  4]
 [19 16]
 [ 9  5]
 [18 10]
 [19 14]
 [ 6  9]]
(6, 2)
